main:
  - name: About me
    pageRef: /about
    weight: 80
    params:
      icon: about

  - name: Focus
    pageRef: /focus
    weight: 81
    params:
      icon: lightbulb

  - name: Portfolio
    weight: 90
    pageRef: /projects
    params:
      icon: projects

  - name: Posts
    pageRef: /posts
    weight: 100
    params:
      icon: posts

#  - name: Archives
#    pageRef: /archives
#    weight: 20
#    params:
#      icon: archive

#  # Example: parent item with dropdown submenu children
#  - name: More
#    weight: 30
#    params:
#      icon: layers

#  - name: Categories
#    weight: 1
#    pageRef: /categories
#    parent: More
#    params:
#      icon: categories

#  - name: Tags
#    weight: 2
#    pageRef: /tags
#    parent: More
#    params:
#      icon: tags

#  - name: Series
#    weight: 3
#    pageRef: /series
#    parent: More
#    params:
#      icon: bookmark

#  - name: Projects
#    weight: 4
#    pageRef: /projects
#    parent: More
#    params:
#      icon: projects



# footer menu
footer:
  - name: Timeline
    pageRef: /timeline
    weight: 10
    params:
      icon: chart

  - name: About
    pageRef: /about
    weight: 20
    params:
      icon: about

  - name: RSS Feed
    url: /index.xml
    weight: 30
    params:
      icon: rss

# footer social link
social:
  - name: GitHub
    url: https://github.com/k42um
    weight: 10
    params:
      icon: github
  - name: X
    url: https://twitter.com/k42uma
    weight: 20
    params:
      icon: X
  - name: LinkedIn
    url: https://linkedin.com/in/k42uma
    weight: 30
    params:
      icon: linkedin
#  - name: Email
#    url: mailto:your.email@example.com
#    weight: 40
#    params:
#      icon: email
  - name: Zenn
    url: https://zenn.dev/k42uma
    weight: 40
    params:
      icon: Zenn
